version: "3"

networks:
  mqttnetwork:
    external: true

services:
  janus:
    build:
      dockerfile: Dockerfile
    container_name: janus
    restart: always
    ports:
      - 8088:8088
      - 8089:8089
      - 8188:8188
      - 8989:8989
    volumes:
      - ./janus.jcfg:/etc/janus/janus.jcfg
      - ./janus.transport.http.jcfg:/etc/janus/janus.transport.http.jcfg
      - ./janus.transport.websockets.jcfg:/etc/janus/janus.transport.websockets.jcfg
    networks:
      - mqttnetwork
